name: Test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: |
          python rho_pollard.py
          if [[ ! $(python rho_pollard.py) == 28 ]]; then
            echo "First test failed"
            exit 1
          fi  

